spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/sofia?useUnicode=true&characterEncoding=UTF-8&connectionTimeZone=UTC}
    username: ${DB_USERNAME:sofia}
    password: ${DB_PASSWORD:sofia}
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true
