spring:
  application:
    name: sofia
  datasource:
    url: ${SOFIA_DATASOURCE_URL}?prepareThreshold=0&preparedStatementCacheQueries=0&preferQueryMode=simple # https://jdbc.postgresql.org/documentation/use/
    username: ${SOFIA_DATASOURCE_USERNAME}
    password: ${SOFIA_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    type: org.springframework.jdbc.datasource.DriverManagerDataSource # Do not use HikariCP
  mail:
    host: localhost
    port: 25
  jpa:
    properties:
      org.hibernate.envers:
        audit_table_suffix: _audit
        audit_strategy: org.hibernate.envers.strategy.DefaultAuditStrategy
    open-in-view: false
    hibernate:
      ddl-auto: validate

server:
  forward-headers-strategy: framework

sofia:
  task:
    seconds-per-character: 3.942
    late-threshold-hours: 48
    reminder-enabled: false
  kakao:
    skill:
      secret-token: replace-me-11!!
  first-boot:
    create-admin-if-empty: false
    admin-student-number: 18-100
  email:
    enabled: false
    base-url: sofia-test.ywcheong.com
    from-email: sofia-test@ywcheong.com
    from-name: KSA 국제부 번역버디 ERP
  dummy:
    enabled: false
